require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PagesController do
  let(:user) { Factory(:user) }
  let(:farm) { Factory(:farm) }



  describe 'get home as user' do
    before { get :home }
    before { sign_in user}
    it { should respond_with :success }
    it { should assign_to :farms }
    it { should assign_to :address }
    it { should assign_to :last_activities }
    it { should render_template :home }
    it { should render_template 'layouts/application'}
  end

  describe 'get marketplace as user' do
    before { get :marketplace }
    before { sign_in user }
    it { should respond_with :success }
    it { should assign_to :farms }
    it { should render_template :marketplace }
    it { should render_template 'layouts/application'}
  end

  describe 'route' do
    before {sign_in user}
    before { get :route, :id => farm.id}
    it { should respond_with :success }
    it { should assign_to :farm }
    it { should render_template :route }
    it { should render_template 'layouts/application'}
  end

  describe 'village_board of farm' do
    before { sign_in user }
    before { get :village_board, :farm => farm }
    it { should respond_with :success }
    it { should assign_to :farm }
    it { should assign_to :address }
  end
end
